config/routes.rb
Glossary::Application.routes.draw do
  resources :terms

end

app/models/term.rb
class Term < ActiveRecord::Base
  attr_accessible :name, :slug, :definition

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @terms }
    end
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
    @term = Term.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/new
  # GET /terms/new.json
  def new
    @term = Term.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/1/edit
  def edit
    @term = Term.find(params[:id])
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(params[:term])

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render json: @term, status: :created, location: @term }
      else
        format.html { render action: "new" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /terms/1
  # PUT /terms/1.json
  def update
    @term = Term.find(params[:id])

    respond_to do |format|
      if @term.update_attributes(params[:term])
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glossary</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">
  <h1>Heroku Glossary</h1>
  <ul id="nav">
    <li><%= link_to "All Terms", terms_path %></li>
    <li><%= link_to "New Term", new_term_path %></li>
  </ul>
</div>

<%= yield %>

</body>
</html>

app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :definition %>
    <%= f.text_field :definition %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

app/views/terms/index.html.erb
<ul class="terms">
  <% @terms.each do |term| %>
    <li>
      <h3><%= link_to term.name, term_path(term) %></h3>
      <p> <%= term.definition %></p>
    </li>
  <% end %>
</ul>

app/views/terms/new.html.erb
<h1>New term</h1>

<%= render 'form' %>

<%= link_to 'Back', terms_path %>

app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @term.name %></h2>
<p><%= @term.definition %></p>

<p>
  <%= link_to 'Edit', edit_term_path(@term) %> |
  <%= link_to 'Destroy', @term, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'List all Terms', terms_path %>
</p>